python trajGRU_run.py \
	--gpu 0	\
	--max-epochs 30	\
	--batch-size 5	\
	--lr-scheduler	\
	--weight-decay 0.1	\
	--input-with-grid	\
	--clip	\
	--clip-max-norm	300	\
    --root-dir 01_Radar_data/02_numpy_files	\
    --ty-list-file ty_list.xlsx	\
    --result-dir 04_results/ubuntu	\
	--params-dir 05_params/ubuntu	\
    --I-lat-l 24.6625 --I-lat-h 25.4 --I-lon-l 121.15 --I-lon-h 121.8875 \